import { StyleSheet } from 'react-native';
import { ThemeType } from '../../../constants/theme'; // Ajuste o caminho se necessário

export const createStyles = (theme: ThemeType) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.corFundo,
    paddingHorizontal: 16,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 50,
    paddingBottom: 20,
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: theme.corFonte,
    marginLeft: 10,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
  },
  iconButton: {
    padding: 4,
  },
  heroCard: {
    backgroundColor: theme.roxoPrincipal,
    borderRadius: 16,
    padding: 24,
    marginBottom: 24,
    shadowColor: theme.sombra,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 6,
  },
  badgeAtivos: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    marginBottom: 16,
  },
  badgeText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  heroTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: 12,
    lineHeight: 30,
  },
  heroDescription: {
    fontSize: 15,
    color: '#e0d4f5',
    marginBottom: 24,
    lineHeight: 22,
  },
  heroButtonsContainer: {
    flexDirection: 'column',
    gap: 12,
  },
  btnPrimaryHero: {
    backgroundColor: '#ffffff',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
  },
  btnPrimaryHeroText: {
    color: theme.roxoPrincipal,
    fontWeight: 'bold',
    fontSize: 15,
  },
  btnSecondaryHero: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#ffffff',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
  },
  btnSecondaryHeroText: {
    color: '#ffffff',
    fontWeight: 'bold',
    fontSize: 15,
  },
  sectionContainer: {
    marginBottom: 24,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.corFonte,
  },
  seeAllText: {
    fontSize: 14,
    color: theme.roxoClaro,
    fontWeight: '600',
  },
  cardGrupo: {
    backgroundColor: theme.corSuperficie,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: theme.corBorda,
    shadowColor: theme.sombra,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: theme.corFonte,
    flex: 1,
    marginRight: 10,
  },
  badgeSituacao: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.corSuperficieSecundaria,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 6,
  },
  badgeSituacaoText: {
    fontSize: 11,
    fontWeight: 'bold',
    color: theme.corFonte,
  },
  cardDescription: {
    fontSize: 14,
    color: theme.corFonteSecundaria,
    marginBottom: 16,
    lineHeight: 20,
  },
  cardDetails: {
    gap: 8,
    marginBottom: 16,
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  detailText: {
    fontSize: 13,
    color: theme.corFonteSecundaria,
  },
  btnParticipar: {
    backgroundColor: theme.roxoPrincipal,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  btnParticiparText: {
    color: theme.corFonteInvertida,
    fontWeight: 'bold',
    fontSize: 14,
  },
  ctaCard: {
    backgroundColor: theme.corSuperficieSecundaria,
    borderRadius: 16,
    padding: 24,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: theme.corBorda,
    alignItems: 'center',
  },
  ctaTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.corFonte,
    marginBottom: 12,
    textAlign: 'center',
  },
  ctaDescription: {
    fontSize: 14,
    color: theme.corFonteSecundaria,
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 20,
  },
  btnCta: {
    backgroundColor: theme.roxoPrincipal,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 8,
    width: '100%',
    alignItems: 'center',
  },
  btnCtaText: {
    color: theme.corFonteInvertida,
    fontWeight: 'bold',
    fontSize: 15,
  },
  footer: {
    alignItems: 'center',
    marginTop: 10,
  },
  footerText: {
    color: theme.corFonteSecundaria,
    fontSize: 12,
  },
});